language: csharp

dist: trusty

addons:
  apt:
    packages:
      - python3-pip

solution: src/UnSHACLed.Collaboration/UnSHACLed.Collaboration.sln

install:
  # Grab the requests module. We need it for the tests.
  - sudo pip3 install requests
  # Download NuGet packages.
  - nuget restore src/UnSHACLed.Collaboration/UnSHACLed.Collaboration.sln

script:
  # Build the server.
  - msbuild /p:Configuration=Debug src/UnSHACLed.Collaboration/UnSHACLed.Collaboration.sln
  # Run the unit tests.
  - python3 test/server_tests.py x x
