language: csharp

dist: trusty

addons:
  apt:
    packages:
      - python3-pip

solution: src/UnSHACLed.Collaboration/UnSHACLed.Collaboration.sln

install:
  # Grab the requests module. We need it for the tests.
  - sudo pip3 install requests
  # Download NuGet packages.
  - nuget restore src/UnSHACLed.Collaboration/UnSHACLed.Collaboration.sln

script:
  # Build the server.
  - msbuild /p:Configuration=Debug src/UnSHACLed.Collaboration/UnSHACLed.Collaboration.sln
  # Run the unit tests.
  - python3 test/server_tests.py $CLIENT_ID $CLIENT_SECRET

env:
  global:
    - secure: "sIZzMW9kJPZyeUIXz9NqnospNn++jOiowufJA0X56cc5qyHdiAWuEuj73BZbnp6aApqEU3aDykBgHL/sMQzJqh696J7GN4OwcsIw6RVjccxTPrx3Nsa8EWEutSHxYOtfePqf8OwFDn/sBw2ruqCNZGxw08d0im0Wjn3nAmQ7j0rdUiPQduwxii0FioT4j2k3U3csFsYMa45xcapf7DuPUAqSKOuOfybz4qnq0aV2G1y63/Z1iZUKn/9I+CzYAjEH4e9WL1Ddj/9OzoqhCp/Zc61BlxJ79QMhVJRwyn98ZXAJFCpR9VlEV3BKYwFPQR7RZg1YAvPNqII5sSvVr425AiVq7/WLG+fYxM6Kzc1kGLQcI9R+iUxtv1p5iB13sLqLJHxaffb0BxDT2GM8YULqQn3TzDiqmMRxv/kT79Aq/EZ+5gFUK+B8wLCbZ5CkECyHcVHdLFASwnh6/zn1GEe5S+OLLNM9bkQug+6myAlldePUxRSy25N+16NFJlm/g/q86GgrBunsAioL8XCLvIGW2sXW0g1vc8vpOEQjdKEc2u4qNwDLE69e8Vutpe2VzAF9V0QfBNZM7aVKSeTUhDlpvkz7RUzVfTQUwzuvCgKaYvPnmi9SFbntfG7sVd4M86RTgo86wflG5GxIVfIfBsSNy8M3RUYtZME7ueGeos3D3IE="
    - secure: "nRQHniskEYnJt8dPlO3K2eXX5V9pdwKiZAmwHewDnutXWIQCYz/p8q9yEXrEplsFZVpOLGJsPiCXfoE0IpejBnG+xHxtJ0AU/+pSdxWDGYevp4O9D99ED/NnnxuZUrRKdfkwABhyqJpHeXju3M3p/T414Zm+EJGDSOGFkSCvB9OtAevZV3gCWXqNE0sHxrCZEvoFiOmtlBR5piUzfvKETKfBU0+Rr/jY+c2ci8iKqeL7LGHwEugE63WpRkfWO5xAZrhPMQgWbsqLopqwOAwZq1mASiqqtY7vhF3XwaupniLNghLzcRrq1Ua88Q3VmqeOpu8vmUAsk/bR2vmvR7LSS9V4RyBAbX6CnYLqktkeYTs49ueqrs4k+syeDymRu6QVJRhdT59S3hi9M5rDTHyHaLGVP/THt3BXHUmRe1G7LyCIh0S65627L86xeSKYaeylSU7An21MY9inaa6BFtjc3V6/qO1/DquNWyeRKBAky+DpfjGzW6lj+gELjgopXRaVyHzyCif4z+YRgkPSKGsCS5q1kqd2d0aIdvwHHwSKYqLPaoNbH/UzxW9Lf3Gxzlgo9mt/eCD+em6E5SaADtmRDxJiT+hE/3+7vWncK6J4w3STsAWirvlmnnRKLJJVaPp/PNBbtVwZvGzelziTX3EUswUsm8qpIb8OGG90dBLTT8c="
